# fly.toml app configuration file generated for flich-valorant-discord-bot on 2024-11-20T17:40:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flich-valorant-discord-bot'
kill_signal = "SIGINT"
kill_timeout = 5

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = "stop"
    auto_start_machines = false
    min_machines_running = 1

[env]

[[vm]]
    memory='256'
    cpu_kind='shared'
    cpus=1