# fly.toml app configuration file generated for flich-valorant-discord-bot on 2024-11-20T17:40:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flich-valorant-discord-bot'

[env]
    PORT = "8080"

[[services]]
    internal_port = 8080
    protocol = "tcp"
    [[services.ports]]
        handlers = ["http"]
        port = 80
        force_https = true
    [[services.ports]]
        handlers = ["tls", "http"]
        port = 443

[[vm]]
    memory='256'
    cpu_kind='shared'
    cpus=1